### ISSUE TITLE
problem when there are many queries on the server

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1071]
We have a view:

https://my.cheminfo.org/?v=v2.87.7&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Fbd334bf1e195901c08390405967453bc%2Fview.json

That gives an error. I don't know if it is related to concurrencies queries ?

**Comment by targos** [comment]
Not sure why you open this here?

Anyway, here is the error:
```
9|rest-on- | 2017-12-20T15:04:06.231Z couch:warn (nano) getDocument failed
9|rest-on- | 2017-12-20T15:04:06.231Z couch:error (middleware:couch) Error: error happened in your connectionError: socket hang up
9|rest-on- |     at createHangUpError (_http_client.js:331:15)
9|rest-on- |     at Socket.socketCloseListener (_http_client.js:363:23)
9|rest-on- |     at emitOne (events.js:121:20)
9|rest-on- |     at Socket.emit (events.js:211:7)
9|rest-on- |     at TCP._handle.close [as _onclose] (net.js:554:12)
```
