### ISSUE TITLE
twig-form generates error in console

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1128]
On the following test view

http://127.0.0.1:5500/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/twig-form/view.json&dataURL=../testcase/data/twig-form/data.json

If you click on the button of the template on the right you have an error:
* Warning: a promise was created in a handler at /127.0.0.1:5500/src/modules/types/display/template-twig/view.js:198:18 but was not returned from it, see http://goo.gl/rRqMUw

If you click twice on send data you have an error:
bluebird.core.js:1417 Unhandled rejection Error: latency    at Variable.triggerChange (http://127.0.0.1:5500/src/src/main/variables.js:156:35)

I spend a while but could not find the reason for this. @targos please could you help me on this.

**Comment by targos** [comment]
It means you have to go from top to bottom of the printed stack trace and make sure that the Promise created at the first line is either handled (with `await` or `.catch`) or returned to the caller (which can then also either handle it or return it, etc...)

![image](https://user-images.githubusercontent.com/2352663/59554965-bc217680-8fab-11e9-978f-d66c8bc66ec1.png)
