### ISSUE TITLE
Slick grid timing problem ??

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#387]
The following page crash from time to time ...

http://www.cheminfo.org/Chemistry/Cheminformatics/Chemical_library.html

With the following error

There is an init script create the default data and I wonder if it could be related to a timing problem.

Possibly unhandled Error: Cannot find stylesheet.
    at getColumnCssRules (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:938:17)
    at applyColumnWidths (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:1107:16)
    at updateCanvasWidth (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:410:9)
    at autosizeColumns (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:1082:7)
    at resizeCanvas (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:1580:9)
    at SlickGrid.finishInitialization [as init] (http://www.lactame.com/visualizer/v2.13.0/components/slickgrid/slick.grid.js:296:9)
    at http://www.lactame.com/visualizer/v2.13.0/modules/types/edition/slick_grid/view.js:1:9891
    at d (http://www.lactame.com/visualizer/v2.13.0/init.js:24:14940)
    at b.exports.b._settlePromiseFromHandler (http://www.lactame.com/visualizer/v2.13.0/init.js:23:20847)
    at b.exports.b._settlePromiseAt (http://www.lactame.com/visualizer/v2.13.0/init.js:23:22174)
    at b.exports.b._settlePromises (http://www.lactame.com/visualizer/v2.13.0/init.js:23:24039)
    at c._drainQueue (http://www.lactame.com/visualizer/v2.13.0/init.js:22:19713)
    at c._drainQueues (http://www.lactame.com/visualizer/v2.13.0/init.js:22:19774)
    at MutationObserver.drainQueues (http://www.lactame.com/visualizer/v2.13.0/init.js:22:18471)

**Comment by stropitek** [comment]
I'm not able to reproduce. But I made a guess fix. You can test if you still have the problem
[here](http://www.cheminfo.org/Chemistry/Cheminformatics/Chemical_library.html?v=head&direct=true)

**Comment by targos** [comment]
I'll close it for now. You can reopen if the problem comes back

**Comment by stropitek** [comment]
This apparently still happens from time to time...

**Comment by stropitek** [comment]
https://github.com/mleibman/SlickGrid/issues/223

**Comment by stropitek** [comment]
@lpatiny
Have you had problems since I last attempted to resolve this?

**Comment by lpatiny** [comment]
Did see the problem recently

**Comment by stropitek** [comment]
Then why close this?

**Comment by lpatiny** [comment]
Sorry .. fixed my previous comments ;)
