### ISSUE TITLE
crash when pasting view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#543]
Unhandled rejection Error: Cannot find stylesheet.
    at getColumnCssRules (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:938:27)
    at applyColumnWidths (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:1107:24)
    at updateCanvasWidth (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:410:17)
    at autosizeColumns (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:1082:13)
    at resizeCanvas (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:1580:17)
    at SlickGrid.finishInitialization [as init] (http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/slick.grid.js:296:17)
    at http://www.lactame.com/visualizer/v2.19.1/modules/types/edition/slick_grid/view.js:1:10851

**Comment by targos** [comment]
Is it a persistent error ? if so could you share the view please ?
related to #387

**Comment by lpatiny** [comment]
No it is not persistent. I got this error when pasting a view and can not reproduce it. I will close it for now ... Hopefully being able to reproduce the bug.
