### ISSUE TITLE
Slick grid generates an error when the array does not exists

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#605]
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at http://www.lactame.com/visualizer/latest/modules/types/edition/slick_grid/view.js:1:4078
    at Array.map (native)
    at i.$.extend.getAllSlickColumns (http://www.lactame.com/visualizer/latest/modules/types/edition/slick_grid/view.js:1:3491)
    at i.$.extend.getSlickColumns (http://www.lactame.com/visualizer/latest/modules/types/edition/slick_grid/view.js:1:4936)
    at a (http://www.lactame.com/visualizer/latest/modules/types/edition/slick_grid/view.js:1:8011)

**Comment by stropitek** [comment]
Can you provide a testcase? The module shouldn't accept anything else than arrays

**Comment by targos** [comment]
Technically one could give an input like
{
  type: "array",
  value: undefined
}

But this must not be handled in the module. It is a user-side error.
