### ISSUE TITLE
Test case stack chart does not work anymore

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#621]
http://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/flotStack/view.json&dataURL=../testcase/data/flotStack/data.json

Error while updating module :  Invalid dimensions for plot, width = null, height = null Error: Invalid dimensions for plot, width = null, height = null
    at Canvas.resize (http://www.lactame.com/visualizer/src/lib/flot/jquery.flot.js:119:10)
    at new Canvas (http://www.lactame.com/visualizer/src/lib/flot/jquery.flot.js:98:8)
    at setupCanvases (http://www.lactame.com/visualizer/src/lib/flot/jquery.flot.js:1283:23)
    at new Plot (http://www.lactame.com/visualizer/src/lib/flot/jquery.flot.js:691:9)
    at Function.$.plot (http://www.lactame.com/visualizer/src/lib/flot/jquery.flot.js:3115:20)
    at View.$.extend.plot (http://www.lactame.com/visualizer/src/modules/types/chart/basic/stack_chart//view.js:225:28)
    at View.$.extend.update.chart (http://www.lactame.com/visualizer/src/modules/types/chart/basic/stack_chart//view.js:79:35)
    at http://www.lactame.com/visualizer/src/modules/default/defaultmodel.js:183:74

**Comment by targos** [comment]
latest working release is v2.8.3: 
http://www.lactame.com/visualizer/v2.8.3/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/flotStack/view.json&dataURL=../testcase/data/flotStack/data.json

Regression must be found between 2.8.3 and 2.9.0: https://github.com/NPellet/visualizer/compare/v2.8.3...v2.9.0
