### ISSUE TITLE
Submitting an issue

### ISSUE THREAD

**Issue by JeffersonH44** [NPellet/visualizer#623]
When I try to send and issue from the visualizer, it throws the following error:

error TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.getDataJSON (http://direct.lactame.com/visualizer/HEAD/src/util/versioning.js:146:25)
    at http://direct.lactame.com/visualizer/HEAD/src/util/couchshare.js:18:75
    at Object.share (http://direct.lactame.com/visualizer/HEAD/src/util/couchshare.js:6:16)
    at Object.exports.feedback.$.html.append.Button.color [as onclick] (http://direct.lactame.com/visualizer/HEAD/src/util/ui.js:210:28)
    at Object.button.doClick (http://direct.lactame.com/visualizer/HEAD/lib/forms/button.js:148:22)
    at HTMLDivElement.<anonymous> (http://direct.lactame.com/visualizer/HEAD/lib/forms/button.js:11:17)
    at HTMLDocument.n.event.dispatch (http://direct.lactame.com/visualizer/HEAD/components/jquery/dist/jquery.min.js:3:6466)
    at HTMLDocument.$event.dispatch (http://direct.lactame.com/visualizer/HEAD/components/slickgrid/lib/jquery.event.drag-2.2.js:374:19)
    at HTMLDocument.$event.dispatch (http://direct.lactame.com/visualizer/HEAD/components/jquery.threedubmedia/event.drag/jquery.event.drag.js:374:19)

**Comment by targos** [comment]
This error means that you have a too big data structure to serialize. There is nothing we can directly do about that, however https://github.com/NPellet/visualizer/issues/564 will allow to select what part of the data is shared when it is done.

**Comment by stropitek** [comment]
@targos are you sure? The error message is misleading then

**Comment by targos** [comment]
I'm sure my first answer is wrong.
`TypeError: Converting circular structure to JSON` means that one object in your data has circular references and so it cannot be converted to JSON because this format has no way to encode such structure.
The only thing you can do is not put this object in the data (if you need a value in scripts but not to display them, you can use [API.cache](http://www.lactame.com/visualizer/doc/api.html) to store and retrive)
