### ISSUE TITLE
pan zoom bug

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#721]
I get the following message:

panzoom: image failed to load Error: Panzoom element must be attached to the document(…)
bluebird.core.min.js:30 Unhandled rejection Error: Panzoom element must be attached to the document
    at Function.n.extend.error (http://www.lactame.com/visualizer/HEAD/components/jquery/dist/jquery.min.js:2:1821)
    at new Panzoom (http://www.lactame.com/visualizer/HEAD/components/jquery.panzoom/dist/jquery.panzoom.js:265:6)

Testcase: http://visualizer.epfl.ch/tiny/UpfqXESci5fM48ShqZMq ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=HEAD&viewURL=%2Fc%2F420cf9177e43f89292d5ca9662d84cb2%2Fview.json))

**Comment by stropitek** [comment]
Can it easily be reproduced? I don't get the error when I just click on images in the table
