### ISSUE TITLE
The button feedback does not work anymore

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#756]
On visualizer.epfl.ch the button feedback yields to:
```
Unhandled rejection TypeError: Cannot read property 'focus' of undefined
    at http://www.lactame.com/visualizer/latest/init.js:17:30954
    at d (http://www.lactame.com/visualizer/latest/init.js:34:17429)
    at b._settlePromiseFromHandler (http://www.lactame.com/visualizer/latest/init.js:34:4129)
    at b._settlePromiseAt (http://www.lactame.com/visualizer/latest/init.js:34:5403)
```

**Comment by targos** [comment]
The button opens a popup window. It was probably blocked by your browser

**Comment by lpatiny** [comment]
Indeed it must be this. Thanks.
